[package]
name = "taur"
version = "0.1.0"
authors = ["Arne Janbu <ajanbu@gmx.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
directories = "2.0"
git2 = "0.10"
raur = "2.0"
structopt = "0.3"
termion = "1.5"
