[package]
name = "taur"
version = "0.1.0"
authors = ["Arne Janbu <ajanbu@gmx.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
directories = "*"
git2 = "*"
raur = "*"
structopt = "*"
termion = "*"
