[package]
name = "taur"
version = "0.1.0"
authors = ["Arne Janbu <ajanbu@gmx.de>"]
license = "GPL-3.0-or-later"
homepage = "https://github.com/arnej/taur"
repository = "https://github.com/arnej/taur.git"
readme = "README.md"
categories = ["command-line-utilities"]
keywords = ["arch", "AUR"]
description = """
A tiny helper for managing AUR package repositories.
"""
edition = "2018"

[dependencies]
directories = "2.0"
git2 = "0.10"
raur = "2.0"
structopt = "0.3"
termion = "1.5"
